#!/usr/bin/env sh
# Copyright (C) 2023 Victor Oliveira <eu@victoroliveira.com.br>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

LABEL=${LABEL:-CPU}
WARN_COLOR=${WARN_COLOR:-#00FFFF}
DANGER_COLOR=${DANGER_COLOR:-#FF0000}
OK_COLOR=${OK_COLOR:-#00FF00}

USAGE=$(mpstat | tail -n 1 | rev | cut -d " " -f1 | rev | awk '{print 100-$1}')

echo $USAGE% # full text
echo $USAGE% # short text

# color
if [[ $USAGE -ge 65 ]]; then
  echo $DANGER_COLOR
elif [[ $USAGE -ge 35 ]]; then
  echo $WARN_COLOR
else
  echo $OK_COLOR
fi

